from pathlib import Path

# Directories — relative to project root so they work whether running
# locally or inside Docker (where WORKDIR is /app)
MODEL_DIR = Path('models')   # gitignored; generated by train.py
PLOTS_DIR = Path('plots')    # committed; generated by train.py
MLFLOW_DIR = Path('mlruns')  # gitignored; written by MLflow automatically
RANDOM_STATE = 42
TEST_SIZE = 0.2

# MLflow — the API service overrides MLFLOW_TRACKING_URI via environment
# variable in docker-compose.yml so it resolves the mlflow container by name
MLFLOW_TRACKING_URI = 'http://localhost:5000'
MLFLOW_EXPERIMENT_NAME = 'credit-risk-scoring'

# Model
TARGET_COLUMN = 'class'
POSITIVE_CLASS = 'bad'  # 'bad' credit = default risk = what we predict
# scikit-learn's fetch_openml returns 'good'/'bad' as strings.
# We encode 'bad' as 1 (the positive class — the risk we care about)
# and 'good' as 0.

# Business cost of errors — standard credit risk assumption.
# A bad loan approved (false negative) costs 5x a good loan rejected (false positive).
# This is a business parameter, not a statistical correction for the imbalance —
# the 70/30 split would only justify a weight of ~2.3, but lenders set it at 5.
CLASS_WEIGHT = {0: 1, 1: 5}
# Passed to sklearn models as class_weight.
# XGBoost uses scale_pos_weight=5 instead — its boosting loss function
# doesn't accept the class_weight dict format that sklearn uses.

# Risk bands — map probability of default to business label.
# Upper bound of last band is 1.01 (not 1.0) so that probability=1.0
# is still caught by the range check in get_risk_band().
RISK_BANDS = {
    (0.0, 0.2):  {'band': 'Low',       'label': 'Approve',           'colour': '#27AE60'},
    (0.2, 0.4):  {'band': 'Medium',    'label': 'Review',            'colour': '#F39C12'},
    (0.4, 0.6):  {'band': 'High',      'label': 'Additional checks', 'colour': '#E67E22'},
    (0.6, 1.01): {'band': 'Very High', 'label': 'Decline',           'colour': '#C0392B'},
}

# Risk score: probability mapped to 0-100 integer (higher = more risk).
# Simple linear mapping: score = int(probability * 100).
# Kept as a formula rather than a function because callers apply it inline.

# Azure
AZURE_APP_NAME = 'credit-risk-scorer'
AZURE_RESOURCE_GROUP = 'credit-risk-rg'
AZURE_LOCATION = 'westeurope'
